// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DevicePublic = {
    device_id: string;
    name: string;
    description?: (string | null);
    location?: (string | null);
    status?: DeviceStatus;
    config?: {
        [key: string]: unknown;
    };
    capabilities?: {
        [key: string]: unknown;
    };
    ip_address?: (string | null);
    last_seen?: (string | null);
    id: string;
    registered_at: string;
    registered_by: (string | null);
};

export type DeviceRegister = {
    device_id: string;
    name: string;
    location?: (string | null);
    capabilities?: {
        [key: string]: unknown;
    };
};

export type DevicesPublic = {
    data: Array<DevicePublic>;
    count: number;
};

export type DeviceStatus = 'online' | 'offline' | 'running';

export type DeviceUpdate = {
    name?: (string | null);
    description?: (string | null);
    location?: (string | null);
    status?: (DeviceStatus | null);
    config?: ({
    [key: string]: unknown;
} | null);
    capabilities?: ({
    [key: string]: unknown;
} | null);
    ip_address?: (string | null);
    last_seen?: (string | null);
};

export type ExperimentCreate = {
    name: string;
    description?: (string | null);
    psyexp_data?: {
        [key: string]: unknown;
    };
    python_code?: (string | null);
    psychojs_code?: (string | null);
    version?: number;
    status?: ExperimentStatus;
    is_active?: boolean;
};

export type ExperimentPublic = {
    name: string;
    description?: (string | null);
    psyexp_data?: {
        [key: string]: unknown;
    };
    python_code?: (string | null);
    psychojs_code?: (string | null);
    version?: number;
    status?: ExperimentStatus;
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
    created_by: string;
};

export type ExperimentsPublic = {
    data: Array<ExperimentPublic>;
    count: number;
};

export type ExperimentStatus = 'draft' | 'compiled' | 'deployed';

export type ExperimentUpdate = {
    name?: (string | null);
    description?: (string | null);
    psyexp_data?: ({
    [key: string]: unknown;
} | null);
    python_code?: (string | null);
    psychojs_code?: (string | null);
    version?: (number | null);
    status?: (ExperimentStatus | null);
    is_active?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DevicesReadDevicesData = {
    limit?: number;
    skip?: number;
};

export type DevicesReadDevicesResponse = (DevicesPublic);

export type DevicesRegisterDeviceData = {
    requestBody: DeviceRegister;
};

export type DevicesRegisterDeviceResponse = (DevicePublic);

export type DevicesReadDeviceData = {
    id: string;
};

export type DevicesReadDeviceResponse = (DevicePublic);

export type DevicesUpdateDeviceData = {
    id: string;
    requestBody: DeviceUpdate;
};

export type DevicesUpdateDeviceResponse = (DevicePublic);

export type DevicesDeleteDeviceData = {
    id: string;
};

export type DevicesDeleteDeviceResponse = (DevicePublic);

export type ExperimentsReadExperimentsData = {
    limit?: number;
    skip?: number;
};

export type ExperimentsReadExperimentsResponse = (ExperimentsPublic);

export type ExperimentsCreateExperimentData = {
    requestBody: ExperimentCreate;
};

export type ExperimentsCreateExperimentResponse = (ExperimentPublic);

export type ExperimentsReadExperimentData = {
    id: string;
};

export type ExperimentsReadExperimentResponse = (ExperimentPublic);

export type ExperimentsUpdateExperimentData = {
    id: string;
    requestBody: ExperimentUpdate;
};

export type ExperimentsUpdateExperimentResponse = (ExperimentPublic);

export type ExperimentsDeleteExperimentData = {
    id: string;
};

export type ExperimentsDeleteExperimentResponse = (ExperimentPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);