/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExperimentsIndexRouteImport } from './routes/_layout/experiments/index'
import { Route as LayoutDevicesIndexRouteImport } from './routes/_layout/devices/index'
import { Route as LayoutExperimentsCreateRouteImport } from './routes/_layout/experiments/create'
import { Route as LayoutDevicesRegisterRouteImport } from './routes/_layout/devices/register'
import { Route as LayoutBuilderIdRouteImport } from './routes/_layout/builder/$id'
import { Route as LayoutExperimentsExperimentIdEditRouteImport } from './routes/_layout/experiments/$experimentId.edit'
import { Route as LayoutExperimentsExperimentIdDetailsRouteImport } from './routes/_layout/experiments/$experimentId.details'
import { Route as LayoutDevicesDeviceIdEditRouteImport } from './routes/_layout/devices/$deviceId.edit'
import { Route as LayoutDevicesDeviceIdDetailsRouteImport } from './routes/_layout/devices/$deviceId.details'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsIndexRoute = LayoutExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesIndexRoute = LayoutDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsCreateRoute = LayoutExperimentsCreateRouteImport.update({
  id: '/experiments/create',
  path: '/experiments/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesRegisterRoute = LayoutDevicesRegisterRouteImport.update({
  id: '/devices/register',
  path: '/devices/register',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuilderIdRoute = LayoutBuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsExperimentIdEditRoute =
  LayoutExperimentsExperimentIdEditRouteImport.update({
    id: '/experiments/$experimentId/edit',
    path: '/experiments/$experimentId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExperimentsExperimentIdDetailsRoute =
  LayoutExperimentsExperimentIdDetailsRouteImport.update({
    id: '/experiments/$experimentId/details',
    path: '/experiments/$experimentId/details',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDevicesDeviceIdEditRoute =
  LayoutDevicesDeviceIdEditRouteImport.update({
    id: '/devices/$deviceId/edit',
    path: '/devices/$deviceId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDevicesDeviceIdDetailsRoute =
  LayoutDevicesDeviceIdDetailsRouteImport.update({
    id: '/devices/$deviceId/details',
    path: '/devices/$deviceId/details',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/builder/$id': typeof LayoutBuilderIdRoute
  '/devices/register': typeof LayoutDevicesRegisterRoute
  '/experiments/create': typeof LayoutExperimentsCreateRoute
  '/devices': typeof LayoutDevicesIndexRoute
  '/experiments': typeof LayoutExperimentsIndexRoute
  '/devices/$deviceId/details': typeof LayoutDevicesDeviceIdDetailsRoute
  '/devices/$deviceId/edit': typeof LayoutDevicesDeviceIdEditRoute
  '/experiments/$experimentId/details': typeof LayoutExperimentsExperimentIdDetailsRoute
  '/experiments/$experimentId/edit': typeof LayoutExperimentsExperimentIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/builder/$id': typeof LayoutBuilderIdRoute
  '/devices/register': typeof LayoutDevicesRegisterRoute
  '/experiments/create': typeof LayoutExperimentsCreateRoute
  '/devices': typeof LayoutDevicesIndexRoute
  '/experiments': typeof LayoutExperimentsIndexRoute
  '/devices/$deviceId/details': typeof LayoutDevicesDeviceIdDetailsRoute
  '/devices/$deviceId/edit': typeof LayoutDevicesDeviceIdEditRoute
  '/experiments/$experimentId/details': typeof LayoutExperimentsExperimentIdDetailsRoute
  '/experiments/$experimentId/edit': typeof LayoutExperimentsExperimentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/builder/$id': typeof LayoutBuilderIdRoute
  '/_layout/devices/register': typeof LayoutDevicesRegisterRoute
  '/_layout/experiments/create': typeof LayoutExperimentsCreateRoute
  '/_layout/devices/': typeof LayoutDevicesIndexRoute
  '/_layout/experiments/': typeof LayoutExperimentsIndexRoute
  '/_layout/devices/$deviceId/details': typeof LayoutDevicesDeviceIdDetailsRoute
  '/_layout/devices/$deviceId/edit': typeof LayoutDevicesDeviceIdEditRoute
  '/_layout/experiments/$experimentId/details': typeof LayoutExperimentsExperimentIdDetailsRoute
  '/_layout/experiments/$experimentId/edit': typeof LayoutExperimentsExperimentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/builder/$id'
    | '/devices/register'
    | '/experiments/create'
    | '/devices'
    | '/experiments'
    | '/devices/$deviceId/details'
    | '/devices/$deviceId/edit'
    | '/experiments/$experimentId/details'
    | '/experiments/$experimentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/builder/$id'
    | '/devices/register'
    | '/experiments/create'
    | '/devices'
    | '/experiments'
    | '/devices/$deviceId/details'
    | '/devices/$deviceId/edit'
    | '/experiments/$experimentId/details'
    | '/experiments/$experimentId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/builder/$id'
    | '/_layout/devices/register'
    | '/_layout/experiments/create'
    | '/_layout/devices/'
    | '/_layout/experiments/'
    | '/_layout/devices/$deviceId/details'
    | '/_layout/devices/$deviceId/edit'
    | '/_layout/experiments/$experimentId/details'
    | '/_layout/experiments/$experimentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments/': {
      id: '/_layout/experiments/'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof LayoutExperimentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices/': {
      id: '/_layout/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments/create': {
      id: '/_layout/experiments/create'
      path: '/experiments/create'
      fullPath: '/experiments/create'
      preLoaderRoute: typeof LayoutExperimentsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices/register': {
      id: '/_layout/devices/register'
      path: '/devices/register'
      fullPath: '/devices/register'
      preLoaderRoute: typeof LayoutDevicesRegisterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builder/$id': {
      id: '/_layout/builder/$id'
      path: '/builder/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof LayoutBuilderIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments/$experimentId/edit': {
      id: '/_layout/experiments/$experimentId/edit'
      path: '/experiments/$experimentId/edit'
      fullPath: '/experiments/$experimentId/edit'
      preLoaderRoute: typeof LayoutExperimentsExperimentIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments/$experimentId/details': {
      id: '/_layout/experiments/$experimentId/details'
      path: '/experiments/$experimentId/details'
      fullPath: '/experiments/$experimentId/details'
      preLoaderRoute: typeof LayoutExperimentsExperimentIdDetailsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices/$deviceId/edit': {
      id: '/_layout/devices/$deviceId/edit'
      path: '/devices/$deviceId/edit'
      fullPath: '/devices/$deviceId/edit'
      preLoaderRoute: typeof LayoutDevicesDeviceIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices/$deviceId/details': {
      id: '/_layout/devices/$deviceId/details'
      path: '/devices/$deviceId/details'
      fullPath: '/devices/$deviceId/details'
      preLoaderRoute: typeof LayoutDevicesDeviceIdDetailsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBuilderIdRoute: typeof LayoutBuilderIdRoute
  LayoutDevicesRegisterRoute: typeof LayoutDevicesRegisterRoute
  LayoutExperimentsCreateRoute: typeof LayoutExperimentsCreateRoute
  LayoutDevicesIndexRoute: typeof LayoutDevicesIndexRoute
  LayoutExperimentsIndexRoute: typeof LayoutExperimentsIndexRoute
  LayoutDevicesDeviceIdDetailsRoute: typeof LayoutDevicesDeviceIdDetailsRoute
  LayoutDevicesDeviceIdEditRoute: typeof LayoutDevicesDeviceIdEditRoute
  LayoutExperimentsExperimentIdDetailsRoute: typeof LayoutExperimentsExperimentIdDetailsRoute
  LayoutExperimentsExperimentIdEditRoute: typeof LayoutExperimentsExperimentIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBuilderIdRoute: LayoutBuilderIdRoute,
  LayoutDevicesRegisterRoute: LayoutDevicesRegisterRoute,
  LayoutExperimentsCreateRoute: LayoutExperimentsCreateRoute,
  LayoutDevicesIndexRoute: LayoutDevicesIndexRoute,
  LayoutExperimentsIndexRoute: LayoutExperimentsIndexRoute,
  LayoutDevicesDeviceIdDetailsRoute: LayoutDevicesDeviceIdDetailsRoute,
  LayoutDevicesDeviceIdEditRoute: LayoutDevicesDeviceIdEditRoute,
  LayoutExperimentsExperimentIdDetailsRoute:
    LayoutExperimentsExperimentIdDetailsRoute,
  LayoutExperimentsExperimentIdEditRoute:
    LayoutExperimentsExperimentIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
